name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Build
        run: |
          (
            cd ~
            wget https://github.com/juce-framework/JUCE/releases/download/6.0.4/juce-6.0.4-osx.zip
            unzip ./juce-6.0.4-osx.zip
            rm ./juce-6.0.4-osx.zip
          )

          plugins=('Chorus' 'Compressor-Expander' 'Delay' 'Distortion' 'Flanger' 'Panning' 'Parametric EQ' 'Phaser' 'Ping-Pong Delay' 'Pitch Shift' 'Ring Modulation' 'Robotization-Whisperization' 'Template Frequency Domain' 'Template Time Domain' 'Tremolo' 'Vibrato' 'Wah-Wah')
          for p in "${plugins[@]}"; do
            (
              cd ${p}
              ~/JUCE/Projucer.app/Contents/MacOS/Projucer --resave ${p}.jucer
              xcodebuild -project ./Builds/MacOSX/${p}.xcodeproj -alltargets -configuration Release -arch $(uname -m)
              cd ./Products
              zip -r ${p}.zip ./*
            )
          done

      - name: Upload zipped artefacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./**/Products/*.zip
          if-no-files-found: error
