name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        plugin: ['Chorus', 'Compressor-Expander', 'Delay', 'Distortion', 'Flanger', 'Panning', 'Parametric EQ', 'Phaser', 'Ping-Pong Delay', 'Pitch Shift', 'Ring Modulation', 'Robotization-Whisperization', 'Template Frequency Domain', 'Template Time Domain', 'Tremolo', 'Vibrato', 'Wah-Wah']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Build
        run: |
          cd ~
          wget https://github.com/juce-framework/JUCE/releases/download/6.0.4/juce-6.0.4-osx.zip
          unzip ./juce-6.0.4-osx.zip
          rm ./juce-6.0.4-osx.zip

          cd "${{github.workspace }}/${{ matrix.plugin }}"
          ~/JUCE/Projucer.app/Contents/MacOS/Projucer --resave "${{ matrix.plugin }}.jucer"
          xcodebuild -project "./Builds/MacOSX/${{ matrix.plugin }}.xcodeproj" -alltargets -configuration Release -arch $(uname -m)
          cd "${{github.workspace }}/${{ matrix.plugin }}/Products"
          zip -r "${{ matrix.plugin }}.zip" ./*

      # TODO: match format of https://github.com/juandagilc/Audio-Effects/releases/tag/v1.0.0
      #
      # Standalone.macOS.zip
      # Standalone.Windows.zip
      # VST3.macOS.zip
      # VST3.Windows.zip
      - name: Upload zipped artefacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{github.workspace }}/${{ matrix.plugin }}/Products/*.zip
          if-no-files-found: error
